language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
- mvn -P coverall clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: YB2JGmVsOS8QHSntm4PMxoglV4QZa5g4G056AuH0O8zWyo7W0ZytRTdlvvGY83gw+VBiFXdDpQSGuBhsh80InlrqCUutbBlBaUUem/0TGieKLvFmDpjCxcDEJOC3FslIdNLSBaluJxvHr6UG3nJCyw+QRl+j9hkHXBEiMRHf+Okhm573//hNyO6AlXpFpgYkXAdLFpexFL48MHuHRmQqS1ibQ5Q7jfZMxbuhHSrPQC72a8xVHoeO8fWjqjdVbcBKrxDPA8vTD8k84bbIb6N/tAjChi8ld2hsCW7MU8ADG0T6oQk3Ccj+ftVSUGgbl4Q7UaYwv5OCPkCfRNf9bMLS8D0xEGgLosfVCnpA2zDi0k1kfWBzYfVkOShMPMbz2ASf79/8+ZoTeYeZ3Cm10mwmJoT+6O7NK7pjXrUSvoD4ErcNBvHOqCxqkOpPHBmpo1OFLPP/QfPe4VgasuonUuMtjsPnW6jHaQOc/XJ17CJIZk1iSoWWYaopdo3GYDsl50Vf4YFSGrg4oNrCCtLXoA4hV3v83au2vFVNu3cw+U+7JBR0EA3Nhe+jrSqpixYU5POF3iDuOqari7sZnpOhZD/hn9IEdaUGWhhdRdgu3PCD/mKIGo0tDiN6CoR5LWw9UimNhTKDFG1PTjrhuK3avOX/MBv+Ug5JpHie1oKG8i+3cWc=
